//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kosstore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScriptCategory
    {
        public ScriptCategory()
        {
            this.Scripts = new HashSet<Script>();
        }
    
        public int ID { get; set; }
        public string CategoryName { get; set; }
        public string CategoryDescription { get; set; }
        public Nullable<int> ParentCategory { get; set; }
    
        public virtual ICollection<Script> Scripts { get; set; }
    }
}
