//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kosstore.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class kosEntities : DbContext
    {
        public kosEntities()
            : base("name=kosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Script> Scripts { get; set; }
        public DbSet<UserProfileEF> UserProfileEFs { get; set; }
        public DbSet<ScriptComment> ScriptComments { get; set; }
        public DbSet<Like> Likes { get; set; }
    }
}
