//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kosstore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfileEF
    {
        public UserProfileEF()
        {
            this.Scripts = new HashSet<Script>();
            this.ScriptComments = new HashSet<ScriptComment>();
            this.Likes = new HashSet<Like>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<Script> Scripts { get; set; }
        public virtual ICollection<ScriptComment> ScriptComments { get; set; }
        public virtual ICollection<Like> Likes { get; set; }
    }
}
